# Generated by Django 5.0.6 on 2024-05-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configflags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
